// <auto-generated />
using System;
using HeThongMuonTraSachThuVien.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongMuonTraSachThuVien.Migrations
{
    [DbContext(typeof(ThuVienDbContext))]
    [Migration("20260925033107_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongMuonTraSachThuVien.Models.BanDoc", b =>
                {
                    b.Property<int>("BanDocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BanDocID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BanDocId"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("MaBanDoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())", "DF_BanDoc_NgayDangKy");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_BanDoc_TrangThai");

                    b.HasKey("BanDocId");

                    b.HasIndex(new[] { "MaBanDoc" }, "IX_BanDoc_MaBanDoc");

                    b.HasIndex(new[] { "MaBanDoc" }, "UQ_BanDoc_MaBanDoc")
                        .IsUnique();

                    b.HasIndex(new[] { "NguoiDungId" }, "UQ_BanDoc_NguoiDungID")
                        .IsUnique();

                    b.ToTable("BanDoc");
                });

            modelBuilder.Entity("HeThongMuonTraSachThuVien.Models.ChinhSachMuon", b =>
                {
                    b.Property<int>("ChinhSachMuonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChinhSachMuonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChinhSachMuonId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LoaiTheId")
                        .HasColumnType("int")
                        .HasColumnName("LoaiTheID");

                    b.Property<decimal>("MucPhatHuHong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MucPhatMatSach")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MucPhatTreHanMoiNgay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("NgayApDung")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())", "DF_ChinhSachMuon_NgayTao");

                    b.Property<int?>("NguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<byte>("SoLanGiaHanToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1, "DF_ChinhSachMuon_SoLanGiaHanToiDa");

                    b.Property<short>("SoNgayMuonToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)14, "DF_ChinhSachMuon_SoNgayMuonToiDa");

                    b.Property<byte>("SoSachToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)5, "DF_ChinhSachMuon_SoSachToiDa");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_ChinhSachMuon_TrangThai");

                    b.HasKey("ChinhSachMuonId");

                    b.HasIndex(new[] { "LoaiTheId" }, "IX_ChinhSachMuon_LoaiThe");

                    b.HasIndex(new[] { "NgayApDung" }, "IX_ChinhSachMuon_NgayApDung");

                    b.HasIndex(new[] { "TrangThai" }, "IX_ChinhSachMuon_TrangThai");

                    b.ToTable("ChinhSachMuon");
                });

            modelBuilder.Entity("HeThongMuonTraSachThuVien.Models.LoaiThe", b =>
                {
                    b.Property<int>("LoaiTheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoaiTheID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiTheId"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())", "DF_LoaiThe_NgayTao");

                    b.Property<int?>("NguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<decimal>("PhiDangKy")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenLoaiThe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_LoaiThe_TrangThai");

                    b.HasKey("LoaiTheId");

                    b.HasIndex(new[] { "TenLoaiThe" }, "IX_LoaiThe_TenLoaiThe");

                    b.HasIndex(new[] { "TrangThai" }, "IX_LoaiThe_TrangThai");

                    b.HasIndex(new[] { "TenLoaiThe" }, "UQ_LoaiThe_TenLoaiThe")
                        .IsUnique();

                    b.ToTable("LoaiThe");
                });

            modelBuilder.Entity("HeThongMuonTraSachThuVien.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungId"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())", "DF_NguoiDung_NgayTao");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_NguoiDung_TrangThai");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    b.HasKey("NguoiDungId");

                    b.HasIndex(new[] { "Email" }, "IX_NguoiDung_Email");

                    b.HasIndex(new[] { "TenDangNhap" }, "IX_NguoiDung_TenDangNhap");

                    b.HasIndex(new[] { "VaiTroId" }, "IX_NguoiDung_VaiTro");

                    b.HasIndex(new[] { "Email" }, "UQ_NguoiDung_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ_NguoiDung_TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("HeThongMuonTraSachThuVien.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NhanVienID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_NhanVien_TrangThai");

                    b.HasKey("NhanVienId");

                    b.HasIndex(new[] { "MaNhanVien" }, "IX_NhanVien_MaNhanVien");

                    b.HasIndex(new[] { "MaNhanVien" }, "UQ_NhanVien_MaNhanVien")
                        .IsUnique();

                    b.HasIndex(new[] { "NguoiDungId" }, "UQ_NhanVien_NguoiDungID")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("HeThongMuonTraSachThuVien.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("NhatKyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NhatKyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhatKyId"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("DoiTuong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NguoiThucHienId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiThucHienID");

                    b.Property<string>("TenNguoiThucHien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())", "DF_NhatKyHeThong_ThoiGian");

                    b.HasKey("NhatKyId");

                    b.HasIndex(new[] { "HanhDong" }, "IX_NhatKyHeThong_HanhDong");

                    b.HasIndex(new[] { "TenNguoiThucHien" }, "IX_NhatKyHeThong_TenNguoiThucHien");

                    b.HasIndex(new[] { "ThoiGian" }, "IX_NhatKyHeThong_ThoiGian");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("HeThongMuonTraSachThuVien.Models.TheThuVien", b =>
                {
                    b.Property<int>("TheThuVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TheThuVienID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheThuVienId"));

                    b.Property<int>("BanDocId")
                        .HasColumnType("int")
                        .HasColumnName("BanDocID");

                    b.Property<int>("LoaiTheId")
                        .HasColumnType("int")
                        .HasColumnName("LoaiTheID");

                    b.Property<string>("LyDoKhoa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MaThe")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateOnly>("NgayCap")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())", "DF_TheThuVien_NgayTao");

                    b.Property<int?>("NguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<byte>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1, "DF_TheThuVien_TrangThai");

                    b.HasKey("TheThuVienId");

                    b.HasIndex(new[] { "BanDocId" }, "IX_TheThuVien_BanDoc");

                    b.HasIndex(new[] { "MaThe" }, "IX_TheThuVien_MaThe");

                    b.HasIndex(new[] { "TrangThai" }, "IX_TheThuVien_TrangThai");

                    b.HasIndex(new[] { "MaThe" }, "UQ_TheThuVien_MaThe")
                        .IsUnique();

                    b.ToTable("TheThuVien");
                });

            modelBuilder.Entity("HeThongMuonTraSachThuVien.Models.VaiTro", b =>
                {
                    b.Property<int>("VaiTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaiTroId"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_VaiTro_TrangThai");

                    b.HasKey("VaiTroId");

                    b.HasIndex(new[] { "TenVaiTro" }, "IX_VaiTro_TenVaiTro");

                    b.HasIndex(new[] { "TenVaiTro" }, "UQ_VaiTro_TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro");
                });
#pragma warning restore 612, 618
        }
    }
}
